#!/bin/sh
# readmes - shows readme files' names and contents

find . -iname '*readme*' \
       ! -name 'readmes' \
       -printf '%p:\n\n' \
       -execdir sed 's/^/   /' {} \; \
       -printf '\n' |
    less
